### ISSUE TITLE
 Issue with ligatures

### ISSUE THREAD

**Issue by ratfox** [google/roboto#189]
Not all products use the triple ligatures ffi and ffl. Google products, for instance, use fi and fl, but not ffi and ffl.

In some sizes, particularly in 12pt, that means that in words like efficient and affluent, the bars of the two f's are not aligned. Which is not pretty.

**Comment by jamesgk** [comment]
The cause of this can be seen in the [dlig and liga feature source](https://github.com/google/roboto/blob/4ee04b9735ff0d252124816c3413d37eddf204fe/src/v2/Roboto_Regular.ufo/features.fea#L683) (which has never changed in v2).

In `liga`, one can only get ffi through f_f + i, but can only get f_f through the `dlig` feature which by my understanding is not active by default. @roozbehp, can you advise? My thinking is we want to simply change the ffi substitution to f + f + i (and similarly for ffl).

**Comment by adrientetar** [comment]
I think the current feature code somehow assumes that dlig will be on all the time, which is wrong. We should put optional feature after the always-on one, i.e.:

1. use f f in the liga block instead of f_f
2. put dlig after liga such that sub f f by f_f will only happen if no f_f_i ligature was substituted already.
