### ISSUE TITLE
What's the difference between roboto-android and roboto-unhinted?

### ISSUE THREAD

**Issue by xmllmx** [google/roboto#196]
Google says:

> Hinted fonts
> 
> Hints are the instructions embedded in a font on how to modify (distort) a glyph 
> to look better on low-resolution displays. As a tradeoff, a hinted font consumes
> more space than the unhinted version.
> 
> Both Roboto and Noto have hinted and unhinted versions. Google recommends:
> - Use the unhinted versions on Android and on Mac OS X, which doesn’t implement hints.
> 
> -  Use hinted fonts on Chrome OS, Windows, and Linux.

What's the difference between roboto-android and roboto-unhinted?

see also: http://stackoverflow.com/questions/38118283/whats-the-difference-between-roboto-android-and-roboto-unhinted

**Comment by jamesgk** [comment]
See here for a detailed description of hinting:
https://en.wikipedia.org/wiki/Font_hinting

But practically speaking, this is what happens if you use unhinted Roboto on Windows:
https://github.com/google/roboto/issues/174

This is because the hinted versions contain more data to help Windows fit contours to pixels. But since this data makes the font files significantly larger, you should probably try to use the unhinted versions whenever possible. I actually would not recommend using hinted fonts on *any* platform other than Windows, including Linux. Unhinted Roboto looks fine on Linux in my experience.

**Comment by jamesgk** [comment]
Whoops, misread your question as the difference between hinted and unhinted. The differences between roboto-unhinted and roboto-android are: 1) The Android version has had glyph outlines optimized and some data dropped which Android doesn't use anyways. You can see this in the smaller font file sizes. 2) The metrics of the font are manually set to be compatible with older versions of Roboto, with values that the Android operating system expects.
