### ISSUE TITLE
Convert build chain to fontmake

### ISSUE THREAD

**Issue by m4rc1e** [google/roboto#239]
Currently the chain consists of Robofab and some super old dependencies. If this project continues, it may be wise to invest the time and move it to [fontmake](https://github.com/googlei18n/fontmake)

In the process this should solve #234 and #55.

**Comment by jamesgk** [comment]
I started a "fontmake" branch for this, but hit a wall trying to port the italicizing code to Defcon. More recently, more comprehensive masters have been under development so that automatic italicizing (which was always a bit of a dark art) and other weird steps can be removed from the build process entirely, then we can basically just store masters here and use fontmake.

**Comment by davelab6** [comment]
I propose to "backport" the release TTFs into 'source' UFOs that fontmake can compile; and make them interpolatable such that a variable font is possible; no port of italicizing code required.

**Comment by madig** [comment]
Any news on fontmake efforts or these new masters?

**Comment by davelab6** [comment]
See github.com/typenetwork/toboto

**Comment by davelab6** [comment]
Closing since this was done there
