### ISSUE TITLE
Lower case letter height changed?

### ISSUE THREAD

**Issue by mjamin** [google/roboto#243]
Going from `v15` to `v16` (fonts.google.com) changes the height of lower case letters. Anyone using a `https://fonts.googleapis.com/css?family=Roboto` link on their website will suddenly see a significant and possibly very unwanted difference.

[v15](https://fonts.gstatic.com/s/roboto/v15/CWB0XYA8bzo0kSThX0UTuA.woff2) (left), [v16](https://fonts.gstatic.com/s/roboto/v16/CWB0XYA8bzo0kSThX0UTuA.woff2) (right):

![Roboto](http://i.imgur.com/DeniX95.png)

The fonts.google.com preview itself still uses v15 which makes it even more confusing.

**Comment by m4rc1e** [comment]
@mjamin The v2.000 webfonts were released when this issue occurred, #68. Back then, the hinting was incorrect when compared to the v1.000 fonts. Since the v2.000 webfonts were released several years ago, this regression has become a feature.

I have spent a lot of time testing this issue as documented in the pr to fonts/google, https://github.com/google/fonts/pull/710. I've also tested various platforms and have a separate testing repo, https://github.com/googlefonts/robototester. Check out the before and after gifs in the releases. 

the x-height change affects Windows platforms only.

**Comment by thesilentw** [comment]
So, what, we're supposed to just ignore the fact that most font display in most website in Chrome is now showing up in a completely undesired way that isn't how 90% of users expect it? How do we escalate this issue to someone who's willing to roll back the change?

**Comment by atomicthumbs** [comment]
So someone wrecked a crapload of websites and it's not a bug?

**Comment by Rinux55** [comment]
I have the same issue. Our whole app looks weirdly 'narrow' now.

**Comment by JonET** [comment]
I love the open source community.
