### ISSUE TITLE
 Stretched font in Windows (my last question on this error)

### ISSUE THREAD

**Issue by Wladkh** [google/roboto#246]
Sorry that I'm bothering you, but I'm interested in the final answer. Tell me, please, in the next version of Roboto error with the display of fonts in Windows (elongated letters on even sizes 14/16/18px...) will be fixed?
Or the font in Windows will remain elongated?
I ask, since I need to find the optimal solution, either to abandon Roboto, or to write a script for the old version, or to wait for the error to be fixed.
Thank you!

**Comment by Rinux55** [comment]
Sorry guys. don't want to be rude, I really appreciate the work you are doing on this project. 

But I can't really wrap my head around the fact that you release a version of the font which looks bad on very common pixel sizes on one of the most used operating systems, and then ignore any complaints by saying it won't be changed anytime soon. 

Please tell me, is the way this font is presented now in windows not a hinting bug? Or is it the way it is supposed to look?

**Comment by m4rc1e** [comment]
@Rinux55 see #68 and check the dates.

**Comment by Rinux55** [comment]
Between all the tickets, version numbers and comments I am confused now. Am I saying this correct?
- the way the fonts where hinted in the previous version was a bug introduced some years ago and now you guys fixed it? 

So you are saying that the way the font looks now on windows is not a bug? Even though it looks completely different on a mac?

**Comment by m4rc1e** [comment]
> So you are saying that the way the font looks now on windows is not a bug? Even though it looks completely different on a mac?

The update, v2.137 fixes #68. The previous release was v2.000 which didn't match the original hinting of v1. 

v2.137 matches Mac Os X much better. View it full screen.

![screen shot 2017-04-25 at 09 59 06](https://cloud.githubusercontent.com/assets/7525512/25376953/e7c0af3e-299d-11e7-8279-a7000bc2771b.png)


v15 and v16 refer to the font api.

**Comment by Rinux55** [comment]
Thanks for the more detailed picture. I can see that the height of the font looks better with a ruler. But it also shows what is wrong with the 2.137 version:
![artboard 1](https://cloud.githubusercontent.com/assets/12714499/25377894/104c2a4a-29a9-11e7-9d82-5fd11edf9553.png)

Please check the green marks in the letter 'e'. This is exactly what is making this font looks so narrow now. They may have the same height, but the margins on the inside are different. Don't you agree with me that this looks weird, and that the old version looks much more like the ipad air version?

**Comment by m4rc1e** [comment]
@Rinux55 sorry the image was actually for my mac air. I built a test [site](http://robototester.appspot.com) and have diff browser samples [here](https://github.com/googlefonts/robototester)

This is all rather debatable. Personally, I find the open counter of the 'e' in 2.137 a better match to the mac rendering.

**Comment by Wladkh** [comment]
Here's what the old and new font looks like in my Windows:

<img src="http://fs2.fex.net/get/280399052693/10016996/font.jpg">

http://fs2.fex.net/get/280399052693/10016996/font.jpg

P.s .: I apologize for my English, I use an interpreter

**Comment by Rinux55** [comment]
![image](https://cloud.githubusercontent.com/assets/12714499/25379570/bf173d04-29ad-11e7-9532-431090bea4b5.png)
 I have used the roboto tester on a mac, and I do not see a notable difference between old and new. On my windows machine, the difference is huge.

Seeing both new versions of windows and mac to each other, I can see why it may look more the same. But there is this sense of narrowness in the windows version which makes it look so different. I agree, the old version is not perfect next to the mac one, but the personality of the old font is in my opinion much more alike to the mac version.

**Comment by user23145** [comment]
Noticed this as well. Whatever the latest update was, it made the font look significantly worse on the web. It's significantly taller than it used to be, to a point where it looks uncomfortable to the eye to read.

**Comment by thesilentw** [comment]
The kerning is significantly worse in the new version on Windows platforms - the increased x-height makes it more difficult to separate out letters now that there are effectively many more vertical lines, due to the stretched letters.
In many, many other fonts, the established norm is that the letter 'e' is quite close to being a circle, not an oval, and in the new version of Roboto on Windows, it is VERY clearly a vertically oriented oval, not a circle.

Every single one of your users who has taken the time to comment on this issue is telling you that it looks worse, is harder to read, and is an undesired change. Is it really this difficult to admit you might have made a mistake?

**Comment by mattnischan** [comment]
Prior to this change, the ratio of various rounds and bowls was effectively equal height/length. In other words, "o" and it's glyph derivatives were exact circles. After this change, this is no longer the case on Windows.

The question then effectively becomes: Is Roboto intended to have non-circular rounds? If not, then this is a display bug. If Roboto is intended to have ovaled rounds, then the display is correct.

Since the display of Roboto on non-Windows platforms appears to have circular rounds and not ovaled rounds, then I would strongly argue that this is a bug that needs to be corrected as opposed to just a stylistic difference of opinion.

**Comment by mvcoding** [comment]
I have to agree, it's very unpleasant to read now on windows.

**Comment by user23145** [comment]
It's been nearly 2 weeks since the change, and I thought I would've (maybe) been used to the updated font by now, but it's still incredibly hard on the eyes to read. I find myself not only losing lines as I read a page, but also losing words.

I can't imagine how hard this font is to read for people with dyslexia.

**Comment by fitojb** [comment]
>  Is Roboto intended to have non-circular rounds? If not, then this is a display bug. If Roboto is intended to have ovaled rounds, then the display is correct.

Hm, Roboto has never had circular forms; since it was introduced in Android 4.0, it has been ovaled. Its forms are slightly condensed to allow for more characters to fit in a line, which is a common thing in UI typefaces.

As it was stated previously, the previous look was a hinting regression.

**Comment by davelab6** [comment]
> Is Roboto intended to have non-circular rounds?

Yes. 

> Every single one of your users who has taken the time to comment on this issue is telling you that it looks worse, is harder to read, and is an undesired change. Doesn't that deserve some more thought, or perhaps a review?

Per https://fonts.google.com/specimen/Roboto this is used across 10,000,000 domains. I've seen comments from a few dozen people. It isn't a problem for most people.

**Comment by JohnHernist** [comment]
I'm not that tech savvy so it took me a while to find the right place to complain about this (made a Github account just to make this comment).

But I just want to add to the others' complaints that this has negatively impacted the design of my website and users are complaining about readability issues, as some others have mentioned above.

I think many others who use this font are in the same position that I was in in that I didn't know where to complain about this, but hopefully this is something that is looked into.

**Comment by davelab6** [comment]
@JohnHernist thanks for your comment. I'm sorry to hear of your trouble with the update. If you reduce the font size by 1px, will that help?

**Comment by JohnHernist** [comment]
13px in this version of the font is certainly appears closer to the previous version's 14px, but it still seems quite significantly smaller than the previous version's 14px.

It seems to me that the difference between 13px and 14px is too large.
