### ISSUE TITLE
Add a picture of the font to the README

### ISSUE THREAD

**Issue by kevinburkeshyp** [google/roboto#38]
It would be really nice if you could see an example of the font (or click through a link to see one) in the README - to get a sense for whether I'd like to use it.

**Comment by kkamkou** [comment]
+1

**Comment by waldyrious** [comment]
I suggest linking to https://www.google.com/fonts/specimen/Roboto

**Comment by jamesgk** [comment]
How about an image from the Material Design typography page? http://www.google.com/design/spec/style/typography.html#typography-typeface

**Comment by roozbehp** [comment]
Works for me, assuming we actually generate it using the latest font (using, say, pango-view or hb-view).

**Comment by jamesgk** [comment]
Interestingly, I quickly made a new version of the weight demo with new output and the kerning appears different. Compare the version from the material typography spec:

![live sample](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7ZHlGSHpsMjU5YmM/style_typography_weights1.png)

with the new version I made:

![new sample](https://cloud.githubusercontent.com/assets/988758/8091740/9790cae8-0f6a-11e5-9824-98a1addace1d.png)

It's not a huge difference, but definitely visible. What's odd though is that I've confirmed that the kerning values in the GPOS tables of the new output are consistent with both the old output and the current webfont binaries. Is it possible that the material sample kerning was manipulated somehow, or that it was generated from a version of Roboto I haven't looked at?

Also, since the actual glyphs look identical, do you think it would be okay to link directly to the material images in our readme, despite that the kerning is different?

**Comment by adrientetar** [comment]
It seems the demo picture has had some tracking appliedto the lighter weights. In any case I don't think it's the kerning since even pairs that don't need it appear wider.

**Comment by jamesgk** [comment]
Well, I guess a link to the Fonts page is good enough.
